### ISSUE TITLE
Remove error handler invocation as a result of an unwind

### ISSUE THREAD

**Issue by davidchisnall** [CHERIoT-Platform/cheriot-rtos#302]
Currently, we have the following flow:

1. Compartment A calls compartment B
2. A fault occurs in B.
3. If we force unwind out of B *and* A has an error handler, A's error handler is invoked.

This was useful in the test suite for checking that tests do not terminate unexpectedly.  So far, it has been annoying in 100% of all other cases, and every error handler that we've written has a special case to silently ignore it.

This might not be the worst idea I ever had, but it's definitely near the top of the list.  Removing this path would also simplify the switcher code.

**Comment by rmn30** [comment]
This does seem like it would simplify things and make error handling more predictable but I think it would be good to combine it with compiler warnings about checking result of compartment calls as per https://github.com/CHERIoT-Platform/llvm-project/issues/34
